#! /usr/bin/bash

if [ -d ~/.bash_completions ]; then
    for file in ~/.bash_completions/*; do
        [ -f "$file" ] && . "$file"
    done
fi

if [ -f ~/.config/.exports ]; then
    . ~/.config/.exports
fi

if [ -f "/usr/share/doc/fzf/examples/key-bindings.bash" ]; then
    source /usr/share/doc/fzf/examples/key-bindings.bash
fi


