[analyze]
detect-string-imports = true

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.flake8-type-checking]
strict = true